In [196]:
import numpy as np

R = 3
nb_users = 5
nb_works = 4
nb_tags = 10
U_true = np.random.random((nb_users, R + nb_tags))
VT_true = np.random.random((R, nb_works))
T_true = np.round(np.random.random((nb_works, nb_tags)))
M_true = U_true.dot(np.concatenate((VT_true, T_true.T)))

In [197]:
X = np.array([(i, j) for i in range(nb_users) for j in range(nb_works)])
y = np.array([M_true[i, j] for i in range(nb_users) for j in range(nb_works)])

In [198]:
from sklearn.model_selection import train_test_split

In [199]:
i_train, i_test = train_test_split(range(len(X)), test_size=0.2)

In [200]:
from mangaki.utils.xals import MangakiXALS
from mangaki.utils.als import MangakiALS
from mangaki.utils.svd import MangakiSVD

In [201]:
from mangaki.utils.algo import get_dataset_backup

dataset = get_dataset_backup('als')

In [202]:
svd = MangakiSVD(20)
svd.set_parameters(dataset.anonymized.nb_users, dataset.anonymized.nb_works)

i_train, i_test = train_test_split(range(len(dataset.anonymized.X)), test_size=0.2)

In [203]:
X_train = dataset.anonymized.X[i_train]
y_train = dataset.anonymized.y[i_train]
X_test = dataset.anonymized.X[i_test]
y_test = dataset.anonymized.y[i_test]

In [204]:
svd.fit(dataset.anonymized.X[i_train], dataset.anonymized.y[i_train])
y_pred = svd.predict(X_train)
print('Train error', svd.compute_rmse(y_pred, y_train))
y_pred = svd.predict(X_test)
print('Test error', svd.compute_rmse(y_pred, y_test))

Computing M: (2071 × 10086)


/Users/jilljenn/code/mangaki/mangaki/mangaki/utils/svd.py:36: RuntimeWarning: invalid value encountered in double_scalars
  means[i] = np.sum(matrix[i]) / np.sum(matrix[i] != 0)


Chrono: fill and center matrix [0q, 1464ms]
Shapes (2071, 20) (20,) (20, 10086)
Chrono: factor matrix [0q, 809ms]
Train error 1.07533433827
Test error 1.18274710389


In [213]:
xals = MangakiXALS(20)
#xals.NB_ITERATIONS = 3
xals.set_parameters(dataset.anonymized.nb_users, dataset.anonymized.nb_works)
xals.load_tags()

In [214]:
xals.T.shape

(10086, 503)

In [207]:
from sklearn.decomposition import PCA

pca = PCA(n_components=50)
T_red = pca.fit_transform(xals.T)

In [208]:
pca.explained_variance_ratio_[:40].sum()

0.82833706303687582

In [209]:
xals.load_tags(T_red)

In [210]:
xals.NB_ITERATIONS = 10
xals.fit(dataset.anonymized.X[i_train], dataset.anonymized.y[i_train])
y_pred = xals.predict(X_train)
print('Train error', xals.compute_rmse(y_pred, y_train))
y_pred = xals.predict(X_test)
print('Test error', xals.compute_rmse(y_pred, y_test))

Computing M: (2071 × 10086)
Chrono: fill and center matrix [0q, 3851ms]
Step 0: 5.483739201645807
Step 1: 1.102528355612395
Step 2: 0.9718364676359584
Step 3: 0.9172136307739251
Step 4: 0.8949883762233602
Step 5: 0.8835481302921538
Step 6: 0.8766322063000636
Step 7: 0.8719742823531562
Step 8: 0.8686651774064541
Step 9: 0.866241437661585
Shapes (2071, 70) (70, 10086)
Chrono: factor matrix [0q, 40183ms]
Train error 0.864423050066
Test error 1.15890670955


In [17]:
#y_pred = xals.predict(X_train)
#print('Train error', xals.compute_rmse(y_pred, y_train))
#y_pred = xals.predict(X_test)
#print('Test error', xals.compute_rmse(y_pred, y_test))

In [18]:
#xals = MangakiXALS(10)
#xals.NB_ITERATIONS = 1
#xals.set_parameters(dataset.anonymized.nb_users, dataset.anonymized.nb_works)
#xals.load_tags(np.zeros((5, 2)))

#xals.fit(dataset.anonymized.X[i_train], dataset.anonymized.y[i_train])

In [215]:
als = MangakiALS(10, LAMBDA=0.1)
als.set_parameters(dataset.anonymized.nb_users, dataset.anonymized.nb_works)

als.fit(dataset.anonymized.X[i_train], dataset.anonymized.y[i_train])
y_pred = als.predict(X_train)
print('Train error', als.compute_rmse(y_pred, y_train))
y_pred = als.predict(X_test)
print('Test error', als.compute_rmse(y_pred, y_test))

Computing M: (2071 × 10086)
Chrono: fill and center matrix [0q, 1022ms]
Step 0: 2.9213928218563687
Step 1: 1.1971791822060298
Step 2: 1.0642462239444015
Step 3: 1.0182916541655416
Step 4: 0.9958515595924469
Step 5: 0.9845459536775141
Step 6: 0.9783215335345946
Step 7: 0.9743953561749553
Step 8: 0.9717180378068835
Step 9: 0.9697859948829537
Shapes (2071, 10) (10, 10086)
Chrono: factor matrix [0q, 8286ms]
Train error 0.968331170807
Test error 1.16377260615


In [35]:
als = MangakiALS(10)
als.NB_ITERATIONS = 10
als.set_parameters(dataset.anonymized.nb_users, dataset.anonymized.nb_works)

als.fit(dataset.anonymized.X[i_train], dataset.anonymized.y[i_train])
y_pred = als.predict(X_train)
print('Train error', als.compute_rmse(y_pred, y_train))
y_pred = als.predict(X_test)
print('Test error', als.compute_rmse(y_pred, y_test))

Computing M: (2071 × 10086)
Chrono: fill and center matrix [0q, 888ms]
Step 0: 2.886379284051022
Step 1: 1.194795154319086
Step 2: 1.062144706886434
Step 3: 1.0141357441999006
Step 4: 0.9922552228778776
Step 5: 0.9824491230454211
Step 6: 0.9769894705413208
Step 7: 0.9734309641401508
Step 8: 0.9709293737602634
Step 9: 0.9690863796274234
Shapes (2071, 10) (10, 10086)
Chrono: factor matrix [0q, 7426ms]
Train error 0.967672895872
Test error 1.16500429039


In [216]:
y_train_pred = als.predict(X_train)

In [258]:
from scipy.sparse import coo_matrix

nb_users = dataset.anonymized.nb_users
nb_works = dataset.anonymized.nb_works
row = X_train[:, 0]
col = X_train[:, 1]
data = y_train - y_train_pred
M_res = coo_matrix((data, (row, col)), shape=(nb_users, nb_works)).tocsr()

In [276]:
user_ids = sorted(set(row))

In [277]:
from collections import defaultdict

reg = defaultdict(lambda: LinearRegression())
for user_id in user_ids:
    indices = M_res[user_id].indices
    values = M_res[user_id].data
    reg[user_id].fit(T[indices], values)
    print(user_id)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064
2065
2066
2067
2068
2069
2070


In [245]:
for user_id in M_res:
    print(user_id.__dict__)
    break

{'_shape': (1, 10086), 'maxprint': 50, 'indices': array([  181,   309,   534,   646,  1053,  1278,  1472,  1619,  1674,
        1702,  1850,  2230,  2410,  2676,  2785,  3162,  3240,  3313,
        3368,  3708,  3753,  3778,  4002,  4074,  4204,  4734,  4821,
        4838,  5128,  5180,  5239,  5278,  5327,  5433,  5456,  5502,
        5619,  5659,  5682,  6015,  6104,  6361,  6412,  6547,  7121,
        7436,  7864,  7928,  8555,  8570,  8666,  8684,  8887,  9140,
        9531,  9658,  9868, 10057], dtype=int32), 'indptr': array([ 0, 58], dtype=int32), 'data': array([ 0.84115017, -0.78061279,  0.06992713,  0.41292953, -1.35889697,
        0.21747062,  0.30858745,  0.54244926,  0.13001093, -0.55961203,
       -0.81463369, -0.57074216,  0.44870201, -1.80474958, -1.59269128,
       -1.78490685, -1.52303955, -0.27973057, -1.32619963, -0.53711166,
        0.40461298, -1.22228315,  0.21324886,  1.31921629,  0.32615079,
       -0.0135609 , -1.14372803,  0.50754054, -1.05732752, -0.05187491,


In [239]:
M_res.tocsr()[0, :]

<1x10086 sparse matrix of type '<class 'numpy.float64'>'
	with 58 stored elements in Compressed Sparse Row format>

In [218]:
T = xals.T

In [151]:
T_bin = T > 0

In [152]:
T_bin.sum()

210550

In [219]:
from sklearn.linear_model import LinearRegression

In [194]:

reg = LinearRegression()
reg.fit(T, M_res.T)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [195]:
from sklearn.ensemble import GradientBoostingRegressor
clf = GradientBoostingRegressor()
clf.fit(T, M_res.T)

ValueError: bad input shape (10086, 2071)

In [154]:
W = reg.coef_

In [155]:
W.shape

(2071, 503)

In [156]:
T.shape

(10086, 503)

In [334]:
y_pred = als.predict(X_tmp_test)

In [335]:
len(X_tmp_test)

66730

In [158]:
reg.predict(W).shape

(2071, 2071)

In [159]:
M_res

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.57716627,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [325]:
#M_pred = T.dot(W.T).T
#M_pred[user_id][work_id]
y_delta_res = []
for user_id, work_id in X_tmp_test:
    if user_id not in reg:
        print(user_id, 'not')
        y_delta_res.append(0)
    else:
        y_delta_res.append(reg[user_id].predict(T[work_id].reshape(1, -1))[0])

523 not
1395 not


In [343]:
y_delta_repaired = []
for item in y_delta_res:
    if item < -2:
        y_delta_repaired.append(-2)
    elif item > 2:
        y_delta_repaired.append(2)
    else:
        y_delta_repaired.append(item)

In [346]:
print('Test error', als.compute_rmse(y_pred + y_delta_res, y_tmp_test))

Test error 528004656222.0


# LOL

In [384]:
WINDOW = 70000
print('Test error', als.compute_rmse(y_pred[:WINDOW], y_tmp_test[:WINDOW]))

Test error 1.01114055926


In [385]:
y_new_pred = y_pred + y_delta_repaired
print('Test error', als.compute_rmse(y_new_pred[:WINDOW], y_tmp_test[:WINDOW]))

Test error 0.871027005756


In [109]:
from collections import Counter

nb_ratings = Counter(dataset.anonymized.X[:, 1])

In [110]:
i_test_ordered = sorted(i_test, key=lambda i: nb_ratings[dataset.anonymized.X[i][1]], reverse=True)

In [111]:
X_test_ordered = dataset.anonymized.X[i_test_ordered]
y_test_ordered = dataset.anonymized.y[i_test_ordered]

In [331]:
K = len(X_test_ordered)
X_tmp_test = X_test_ordered[-K:]
y_tmp_test = y_test_ordered[-K:]

In [191]:
y_pred_als = als.predict(X_tmp_test)
print(y_tmp_test[:5])
print(y_pred_als[:5])
print('ALS Test error', als.compute_rmse(y_pred_als, y_tmp_test))
#y_pred_xals = xals.predict(X_tmp_test)
#print('XALS Test error', xals.compute_rmse(y_pred_xals, y_tmp_test))
#print(y_pred_xals[:5])
y_delta_res = []
for user_id, work_id in X_tmp_test:
    y_delta_res.append(M_pred[user_id][work_id])
y_delta_res = np.array(y_delta_res)
y_new = y_pred_als + 2 * y_delta_res
print(y_new[:5])
print(y_delta_res[:5])
print('ALS+delta Test error', als.compute_rmse(y_new, y_tmp_test))

[ 2.   2.  -2.   0.1  2. ]
[ 0.81870445  1.20518091  0.14352004 -0.02111138  0.00179963]
ALS Test error 1.57626977117
[ 0.74814882  1.20518091  0.092865    0.08889291  0.00179963]
[-0.03527782  0.         -0.02532752  0.05500214  0.        ]
ALS+delta Test error 1.56291478683


In [19]:
als = MangakiALS(R + nb_tags, LAMBDA=0.3)
als.NB_ITERATIONS = 20
als.set_parameters(nb_users, nb_works)
als.fit(X[i_train], y[i_train])
#print(xals.U.shape)
#print(xals.U)
y_pred = als.predict(X[i_train])
print('Train error', als.compute_rmse(y_pred, y[i_train]))
y_pred = als.predict(X[i_test])
print(y[i_test])
print(y_pred)
print('Test error', als.compute_rmse(y_pred, y[i_test]))

Computing M: (5 × 4)
Chrono: fill and center matrix [0q, 0ms]
Shapes (5, 13) (13, 4)
Chrono: factor matrix [0q, 13ms]
Train error 0.407541177275
[ 2.25842611  3.07814287  2.53238829  2.79468316]
[ 3.03586777  2.73180058  2.93662579  2.89181462]
Test error 0.473606111409


In [20]:
print(M_true)
print(als.means)
print((als.M.T + als.means).T)

[[ 3.07814287  2.99662165  2.08916146  2.82286951]
 [ 3.12601251  1.87590014  2.53238829  3.58227232]
 [ 2.83954362  2.23948638  2.58370636  2.56809017]
 [ 4.12795464  2.25842611  2.19946811  2.47225194]
 [ 2.43309646  2.52171932  2.79468316  3.34326677]]
[ 2.63621754  2.86139499  2.55770663  2.9332249   2.76602752]
[[ 2.73180058  2.70027044  2.54446537  2.56782888]
 [ 2.86027437  2.63843605  2.93662579  3.00918137]
 [ 2.60100665  2.5191739   2.53868454  2.57140797]
 [ 3.32771838  3.03586777  2.60851086  2.75794132]
 [ 2.64127143  2.66435256  2.89181462  2.86724358]]


In [21]:
xals = MangakiXALS(R, LAMBDA=0.2)
xals.NB_ITERATIONS = 20
xals.load_tags(T_true)
xals.set_parameters(nb_users, nb_works)
xals.fit(X[i_train], y[i_train])
#print(xals.U.shape)
#print(xals.U)
y_pred = xals.predict(X[i_train])
print('Train error', xals.compute_rmse(y_pred, y[i_train]))
y_pred = xals.predict(X[i_test])
#print(y[i_test])
#print(y_pred)
print('Test error', xals.compute_rmse(y_pred, y[i_test]))
print(M_true)
print('means', xals.means)
print((xals.M.T + xals.means).T)
print('V', xals.VT)

Computing M: (5 × 4)
Chrono: fill and center matrix [0q, 1ms]
shape X_train (16, 2)
Step 0: 3.2354964193036886
shape X_train (16, 2)
Step 1: 0.16132774944187103
shape X_train (16, 2)
Step 2: 0.12252481352540687
shape X_train (16, 2)
Step 3: 0.12123771284547814
shape X_train (16, 2)
Step 4: 0.1210336230758187
shape X_train (16, 2)
Step 5: 0.1209886276295622
shape X_train (16, 2)
Step 6: 0.12097541695061939
shape X_train (16, 2)
Step 7: 0.12097081622660022
shape X_train (16, 2)
Step 8: 0.1209690872404515
shape X_train (16, 2)
Step 9: 0.12096841796998646
shape X_train (16, 2)
Step 10: 0.120968156015428
shape X_train (16, 2)
Step 11: 0.12096805305291274
shape X_train (16, 2)
Step 12: 0.12096801251605684
shape X_train (16, 2)
Step 13: 0.12096799654576817
shape X_train (16, 2)
Step 14: 0.12096799025218884
shape X_train (16, 2)
Step 15: 0.1209679877717131
shape X_train (16, 2)
Step 16: 0.120967986794037
shape X_train (16, 2)
Step 17: 0.12096798640867859
shape X_train (16, 2)
Step 18: 0.120967