In [198]:
import numpy as np

N = 100
x = np.round(np.random.random(N)*100)
y_1 = 100*np.random.random(N)-50
y_2 = 100*np.random.random(N)-50

In [199]:
X = np.column_stack((x, y_1, y_2))

In [200]:
y = []
c = 0
for xi, yi1, yi2 in X:
    if xi > 50:
        c += 1
        y.append(yi1)
    else:
        y.append(yi2)

In [201]:
print(np.column_stack((X, y))[:10, :])

[[   5.          -47.67769869    1.21823726    1.21823726]
 [  81.          -17.41261498  -28.10224379  -17.41261498]
 [  83.          -36.18800686  -36.29442923  -36.18800686]
 [  83.           21.45945608  -17.47809508   21.45945608]
 [  87.           37.01776758   17.15705855   37.01776758]
 [  86.          -21.02836231   23.47371204  -21.02836231]
 [  21.          -20.43240476  -36.91857618  -36.91857618]
 [  62.           49.18943506   17.07285866   49.18943506]
 [ 100.           46.90479627  -40.27197465   46.90479627]
 [  17.          -25.13662095   -6.1828661    -6.1828661 ]]


In [202]:
import tensorflow as tf

In [203]:
gamma = tf.Variable(tf.random_normal([1]), name='gamma')

In [244]:
e1 = np.array([1, 0, 0])
e2 = np.array([0, 1, 0])
e3 = np.array([0, 0, 1])
pred = tf.sigmoid(1*(X.dot(e1) - gamma)) * X.dot(e2) + (1 - tf.sigmoid(1*(X.dot(e1) - gamma))) * X.dot(e3)
loss = tf.reduce_mean(tf.square(y - pred))
reg_loss = loss

In [245]:
optimizer = tf.train.AdamOptimizer(1)
train_step = optimizer.minimize(reg_loss, var_list=[gamma])

In [246]:
init_op = tf.global_variables_initializer()
sess = tf.InteractiveSession()
sess.run(init_op)

In [247]:
for i in range(100):
    sess.run(train_step)
    print('loss', sess.run(reg_loss), 'var', gamma.eval())

loss 707.988 var [ 1.98679423]
loss 701.225 var [ 2.93108463]
loss 688.768 var [ 3.82867527]
loss 670.339 var [ 4.71479702]
loss 649.837 var [ 5.62304354]
loss 633.327 var [ 6.56397772]
loss 622.399 var [ 7.51144743]
loss 614.552 var [ 8.43892479]
loss 607.527 var [ 9.33837605]
loss 598.957 var [ 10.22035599]
loss 586.373 var [ 11.10912704]
loss 567.123 var [ 12.0285511]
loss 540.164 var [ 12.98640728]
loss 510.908 var [ 13.97764778]
loss 490.296 var [ 14.99345493]
loss 478.664 var [ 15.99725723]
loss 468.256 var [ 16.97032928]
loss 456.717 var [ 17.92418289]
loss 445.553 var [ 18.86399269]
loss 432.625 var [ 19.7913208]
loss 412.34 var [ 20.72984314]
loss 383.17 var [ 21.7086277]
loss 353.564 var [ 22.73017883]
loss 331.016 var [ 23.77430725]
loss 318.461 var [ 24.81012726]
loss 314.332 var [ 25.7945385]
loss 313.325 var [ 26.70322037]
loss 312.949 var [ 27.53470802]
loss 312.558 var [ 28.2949028]
loss 311.919 var [ 28.99170303]
loss 310.84 var [ 29.63438034]
loss 309.108 var [ 30.233

In [226]:
print(np.column_stack((X, y, pred.eval()))[:10, :])

[[   5.          -47.67769869    1.21823726    1.21823726    1.21823728]
 [  81.          -17.41261498  -28.10224379  -17.41261498  -17.41261482]
 [  83.          -36.18800686  -36.29442923  -36.18800686  -36.18800735]
 [  83.           21.45945608  -17.47809508   21.45945608   21.45945549]
 [  87.           37.01776758   17.15705855   37.01776758   37.01776886]
 [  86.          -21.02836231   23.47371204  -21.02836231  -21.02836227]
 [  21.          -20.43240476  -36.91857618  -36.91857618  -36.91857529]
 [  62.           49.18943506   17.07285866   49.18943506   49.18943405]
 [ 100.           46.90479627  -40.27197465   46.90479627   46.9047966 ]
 [  17.          -25.13662095   -6.1828661    -6.1828661    -6.1828661 ]]


In [227]:
np.round(y) == np.round(pred.eval())

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [228]:
sum(np.round(y) == np.round(pred.eval()))

94